# Generated by Django 5.2 on 2025-05-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('auteur', models.CharField(max_length=200)),
                ('date_publication', models.DateField()),
                ('resume', models.TextField()),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
